### ISSUE TITLE
App crashes with time mode in Android

### ISSUE THREAD

**Issue by saravanakumargn** [react-native-community/datetimepicker#135]
# Bug
Android App crashes with time mode while opening the time picker.
```
    java.lang.IllegalArgumentException: No enum constant com.reactcommunity.rndatetimepicker.RNTimePickerDisplay.CALENDAR
        at java.lang.Enum.valueOf(Enum.java:257)
        at com.reactcommunity.rndatetimepicker.RNTimePickerDisplay.valueOf(RNTimePickerDisplay.java:13)
        at com.reactcommunity.rndatetimepicker.RNTimePickerDialogFragment.getDialog(RNTimePickerDialogFragment.java:60)
        at com.reactcommunity.rndatetimepicker.RNTimePickerDialogFragment.createDialog(RNTimePickerDialogFragment.java:101)
        at com.reactcommunity.rndatetimepicker.RNTimePickerDialogFragment.onCreateDialog(RNTimePickerDialogFragment.java:39)
        at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:403)
```

## Environment info

`react-native info` output:

```bash
info Fetching system and libraries information...
System:
    OS: macOS 10.15.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 121.21 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.14.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.13.1 => 16.13.1 
    react-native: 0.61.5 => 0.61.5
```

Library version: x.x.x

## Steps To Reproduce

1.
```
import DateTimePicker from '@react-native-community/datetimepicker';
```
2.
```
<DateTimePicker
          value={date}
          mode="time"
          onChange={(event, selectedDate) => {
            const currentDate = selectedDate || date;
        
            console.log(currentDate);
          }}
        />
```
...

Describe what you expected to happen:

1.
2.

**Comment by vonovak** [comment]
hello, can you please specify the library version? thanks

**Comment by saravanakumargn** [comment]
datetimepicker version: 
```
"@react-native-community/datetimepicker": "^2.3.0",
```

**Comment by saravanakumargn** [comment]
Added CALENDAR enum in RNTimePickerDisplay and now able to open the time picker.

```
package com.reactcommunity.rndatetimepicker;

/**
 * Date picker display options.
 */
public enum RNTimePickerDisplay {
	CALENDAR,
  CLOCK,
  SPINNER,
  DEFAULT
}
```

**Comment by vonovak** [comment]
hello, I suspect you were trying to open a <DateTimePicker/> with mode="time" and display="calendar" - this is combination that is not allowed. We should cover this in the JS side.
