### ISSUE TITLE
Showing a spinner time picker with custom minute interval crashes on Android R (API 30)

### ISSUE THREAD

**Issue by sjchmiela** [react-native-community/datetimepicker#239]
# Bug report

## Summary

I was trying to import the latest version of this library to Expo so it's available for all Expo users in SDK 39, but I encountered a bug — when I tried to show the spinner time picker with custom minute interval it crashed (I was testing on Android API 30). The same has not crashed on Android API 24.

The crash exception was:
```
2020-08-04 15:32:31.293 24226-24226/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: host.exp.exponent, PID: 24226
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.NumberPicker.setMinValue(int)' on a null object reference
        at versioned.host.exp.exponent.modules.api.components.datetimepicker.MinuteIntervalSnappableTimePickerDialog.setSpinnerDisplayedValues(MinuteIntervalSnappableTimePickerDialog.java:248)
        at versioned.host.exp.exponent.modules.api.components.datetimepicker.MinuteIntervalSnappableTimePickerDialog.setupPickerDialog(MinuteIntervalSnappableTimePickerDialog.java:234)
        at versioned.host.exp.exponent.modules.api.components.datetimepicker.MinuteIntervalSnappableTimePickerDialog.onAttachedToWindow(MinuteIntervalSnappableTimePickerDialog.java:223)
        at versioned.host.exp.exponent.modules.api.components.datetimepicker.RNDismissableTimePickerDialog.onAttachedToWindow(RNDismissableTimePickerDialog.java:37)
        at com.android.internal.policy.DecorView.onAttachedToWindow(DecorView.java:1722)
        at android.view.View.dispatchAttachedToWindow(View.java:20461)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3417)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2391)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1934)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8127)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:731)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
```

## Environment info

`react-native info` output:

Note: I'm running this command inside the `expo` workspace so I don't need to have some of the global packages installed.

```bash
System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 98.12 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.4.0 - /var/folders/d8/g79s05qd0_121z3r66jj72br0000gn/T/yarn--1596547640590-0.9953800870508187/node
    Yarn: 1.22.4 - /var/folders/d8/g79s05qd0_121z3r66jj72br0000gn/T/yarn--1596547640590-0.9953800870508187/yarn
    npm: 6.14.5 - ~/.asdf/installs/nodejs/14.4.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.3 - /Users/sjchmiela/Applications/expo/.direnv/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 2.6.1

## Steps to reproduce

1. Open the example app on an Android API 30 emulator
2. Tap on the <kbd>Show time picker as spinner (with 5 min interval)!</kbd> button.
3. See the app crash.

Describe what you expected to happen:

1. I expected a spinner time picker to be shown.

## Reproducible sample code

```tsx
<DateTimePicker
  value={new Date()} // required, doesn't matter
  minuteInterval={5} // without this prop the app does not crash
  mode="time"
  display="spinner"
/>
```

**Comment by rectified95** [comment]
@sjchmiela Was your previous version of this library 2.6.0? Did this problem occur on it? If you were running an older version, would you please try running this on **2.6.0** and reporting your findings?

**Comment by vonovak** [comment]
I think we can trust that this issue is present ([ere](https://github.com/react-native-community/datetimepicker/blob/480a1b13e8e1c61b8b7c6f38961c7665d5f5ff16/android/src/main/java/com/reactcommunity/rndatetimepicker/MinuteIntervalSnappableTimePickerDialog.java#L248) and anyone is welcome to look into it. I will have time at the end of August maybe.

**Comment by vonovak** [comment]
@sjchmiela can you please share what emulator you used? I tried the following and it worked just fine... Is it using the latest images? Thanks!

<details>
  <summary>expand</summary>

```
Name: Pixel_2_API_30

CPU/ABI: Google Play Intel Atom (x86)

Path: /Users/vojta/.android/avd/Pixel_2_API_30.avd

Target: google_apis_playstore [Google Play] (API level 30)

Skin: pixel_2

SD Card: 512M

fastboot.chosenSnapshotFile: 

runtime.network.speed: full

hw.accelerometer: yes

hw.device.name: pixel_2

hw.lcd.width: 1080

hw.initialOrientation: Portrait

image.androidVersion.api: 30

tag.id: google_apis_playstore

hw.mainKeys: no

hw.camera.front: emulated

avd.ini.displayname: Pixel 2 API 30

hw.gpu.mode: auto

hw.ramSize: 1536

PlayStore.enabled: true

fastboot.forceColdBoot: no

hw.cpu.ncore: 4

hw.keyboard: yes

hw.sensors.proximity: yes

hw.dPad: no

hw.lcd.height: 1920

vm.heapSize: 256

skin.dynamic: yes

hw.device.manufacturer: Google

hw.gps: yes

hw.audioInput: yes

image.sysdir.1: system-images/android-30/google_apis_playstore/x86/

showDeviceFrame: yes

hw.camera.back: virtualscene

AvdId: Pixel_2_API_30

hw.lcd.density: 420

hw.arc: false

hw.device.hash2: MD5:55acbc835978f326788ed66a5cd4c9a7

fastboot.forceChosenSnapshotBoot: no

fastboot.forceFastBoot: yes

hw.trackBall: no

hw.battery: yes

hw.sdCard: yes

tag.display: Google Play

runtime.network.latency: none

disk.dataPartition.size: 6442450944

hw.sensors.orientation: yes

avd.ini.encoding: UTF-8

hw.gpu.enabled: yes
```
</details>

**Comment by sjchmiela** [comment]
Hey! I used the following emulator. Main differences I found are:
- I used Pixel 3 XL instead of Pixel 2
- I used image without Play Store

<summary>
<details>

```
Name: Pixel_3_XL_API_30

CPU/ABI: Google APIs Intel Atom (x86)

Path: /Users/sjchmiela/.android/avd/Pixel_3_XL_API_30.avd

Target: google_apis [Google APIs] (API level 30)

Skin: pixel_3_xl

SD Card: 512M

fastboot.chosenSnapshotFile: 

runtime.network.speed: full

hw.accelerometer: yes

hw.device.name: pixel_3_xl

hw.lcd.width: 1440

hw.initialOrientation: Portrait

image.androidVersion.api: 30

tag.id: google_apis

hw.mainKeys: no

hw.camera.front: emulated

avd.ini.displayname: Pixel 3 XL API 30

hw.gpu.mode: auto

hw.ramSize: 1536

PlayStore.enabled: false

fastboot.forceColdBoot: no

hw.cpu.ncore: 4

hw.keyboard: yes

hw.sensors.proximity: yes

hw.dPad: no

hw.lcd.height: 2960

vm.heapSize: 256

skin.dynamic: yes

hw.device.manufacturer: Google

hw.gps: yes

hw.audioInput: yes

image.sysdir.1: system-images/android-30/google_apis/x86/

showDeviceFrame: yes

hw.camera.back: virtualscene

AvdId: Pixel_3_XL_API_30

hw.lcd.density: 560

hw.arc: false

hw.device.hash2: MD5:9bbaa408d4a8691920c4057ef7844f35

fastboot.forceChosenSnapshotBoot: no

fastboot.forceFastBoot: yes

hw.trackBall: no

hw.battery: yes

hw.sdCard: yes

tag.display: Google APIs

runtime.network.latency: none

disk.dataPartition.size: 6442450944

hw.sensors.orientation: yes

avd.ini.encoding: UTF-8

hw.gpu.enabled: yes
```

</details></summary>

**Comment by vonovak** [comment]
hello @sjchmiela I cannot reproduce it even with Pixel 3 XL without Play Store. Can you please try reproducing it with the example project from this repo so we're certain no expo-specific stuff is interfering (I find it unlikely but 🤷‍♂️ )

did you use compileSdkVersion and targetSdkVersion 29? (I tried both 29 and 30, no luck reproducing)

Thanks!

**Comment by sjchmiela** [comment]
Hey, so sorry for disturbing — it turned out it was an issue with internals of Expo.

- The view wasn't there because
  - the mode was not being set on the dialog because
    - it referenced a React Native resource 
      - which we have prefixed in Expo with `ReactAndroid` (so that we can easily version them and don't get conflicts between different RN versions)

[This](https://github.com/expo/expo/pull/9706/commits/2dd6dd04a5104642f7282debf5cc5a56a6d8262a) fixed it.

Again, sorry for wasting your time! See you in SDK39!

**Comment by vonovak** [comment]
@sjchmiela okay, that's interesting. I still wonder why it worked on one android version and not on the other but happy that it's solved. 

and just fyi, it's possible that there are some other issues that are present in expo but not in vanilla RN: https://github.com/react-native-community/datetimepicker/issues/230

we should probably remove the dependency on the resource from RN core I guess

**Comment by sjchmiela** [comment]
I think #230 is the same as I have encountered, I'll try to fix it in a sec. Thanks for bringing this up!

**Comment by ajacquierbret** [comment]
Hey @sjchmiela and @vonovak !

I'm still facing this issue with Expo Bare Workflow SDK 40.0.1 and @react-native-community/datetimepicker v3.4.2.
I tried to use `expo install` which installed the v3.0.4, but it doesn't solve the problem.

Also tried to apply the followig patch to both v3.0.4 and v3.4.2 versions of the library but it keeps crashing Android devices :

```diff
diff --git a/node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogFragment.java b/node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogFragment.java
index 3466848..03b8eed 100644
--- a/node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogFragment.java
+++ b/node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogFragment.java
@@ -71,8 +71,8 @@ public class RNDatePickerDialogFragment extends DialogFragment {
         case CALENDAR:
         case SPINNER:
           String resourceName = display == RNDatePickerDisplay.CALENDAR
-                  ? "CalendarDatePickerDialog"
-                  : "SpinnerDatePickerDialog";
+                  ? "ReactAndroidCalendarDatePickerDialog"
+                  : "ReactAndroidSpinnerDatePickerDialog";
           return new RNDismissableDatePickerDialog(
                   activityContext,
                   activityContext.getResources().getIdentifier(
diff --git a/node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogFragment.java b/node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogFragment.java
index 0df49a2..f00b3a6 100644
--- a/node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogFragment.java
+++ b/node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogFragment.java
@@ -76,8 +76,8 @@ public class RNTimePickerDialogFragment extends DialogFragment {
         case CLOCK:
         case SPINNER:
           String resourceName = display == RNTimePickerDisplay.CLOCK
-                  ? "ClockTimePickerDialog"
-                  : "SpinnerTimePickerDialog";
+                  ? "ReactAndroidClockTimePickerDialog"
+                  : "ReactAndroidSpinnerTimePickerDialog";
           return new RNDismissableTimePickerDialog(
                   activityContext,
                   activityContext.getResources().getIdentifier(

```

Any help would be greatly appreciated ! 👍
